// <auto-generated />
namespace Live.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tags_Payments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tags_Payments));
        
        string IMigrationMetadata.Id
        {
            get { return "201510011844281_Tags_Payments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
